//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easy_save.Cmd.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easy_save.Cmd.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch of all the processes canceled.
        /// </summary>
        public static string AllProcess_Cancel {
            get {
                return ResourceManager.GetString("AllProcess.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///! Press enter to continue !.
        /// </summary>
        public static string AllProcess_Continue {
            get {
                return ResourceManager.GetString("AllProcess.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; All backup processes have been launched correctly.
        /// </summary>
        public static string AllProcess_EndProcess {
            get {
                return ResourceManager.GetString("AllProcess.EndProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///backup process could not be started.
        /// </summary>
        public static string AllProcess_Error {
            get {
                return ResourceManager.GetString("AllProcess.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File(s) couldn&apos;t be saved.
        /// </summary>
        public static string AllProcess_FileError {
            get {
                return ResourceManager.GetString("AllProcess.FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All files have been saved.
        /// </summary>
        public static string AllProcess_FileSuccess {
            get {
                return ResourceManager.GetString("AllProcess.FileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter [yes] if you want to launch all the save processes, anything other than [yes] will result in a cancel.
        /// </summary>
        public static string AllProcess_StartProcess {
            get {
                return ResourceManager.GetString("AllProcess.StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///! Press enter to continue !.
        /// </summary>
        public static string BackupDetails_Continue {
            get {
                return ResourceManager.GetString("BackupDetails.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; No save work available.
        /// </summary>
        public static string BackupDetails_Empty {
            get {
                return ResourceManager.GetString("BackupDetails.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Here are the available save works :.
        /// </summary>
        public static string BackupDetails_Presentation {
            get {
                return ResourceManager.GetString("BackupDetails.Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cancel.
        /// </summary>
        public static string CancelWord {
            get {
                return ResourceManager.GetString("CancelWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yes.
        /// </summary>
        public static string ConfirmWord {
            get {
                return ResourceManager.GetString("ConfirmWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1| Create a new backup  
        ///2| Remove a backup  
        ///3| Start a backup  
        ///4| Start all available backup processes  
        ///5| View backup details  
        ///6| Exit.
        /// </summary>
        public static string Main_Menu {
            get {
                return ResourceManager.GetString("Main.Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///Enter an option: .
        /// </summary>
        public static string Main_Option {
            get {
                return ResourceManager.GetString("Main.Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; These are your input parameters:.
        /// </summary>
        public static string ParameterPresentation {
            get {
                return ResourceManager.GetString("ParameterPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deletion cancelled.
        /// </summary>
        public static string Remove_Cancel {
            get {
                return ResourceManager.GetString("Remove.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter [yes] to confirm the deletion of :.
        /// </summary>
        public static string Remove_ConfirmChoice {
            get {
                return ResourceManager.GetString("Remove.ConfirmChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , enter [cancel] if you want to cancel the deletion process (leave empty to change name).
        /// </summary>
        public static string Remove_ConfirmChoice2 {
            get {
                return ResourceManager.GetString("Remove.ConfirmChoice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///! Press enter to continue !.
        /// </summary>
        public static string Remove_Continue {
            get {
                return ResourceManager.GetString("Remove.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///=&gt; Backup process not found.
        /// </summary>
        public static string Remove_MissingFile {
            get {
                return ResourceManager.GetString("Remove.MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name of the backup to delete.
        /// </summary>
        public static string Remove_Name {
            get {
                return ResourceManager.GetString("Remove.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; Backup process removed.
        /// </summary>
        public static string Remove_SucessRemove {
            get {
                return ResourceManager.GetString("Remove.SucessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation cancelled.
        /// </summary>
        public static string Save_Cancel {
            get {
                return ResourceManager.GetString("Save.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter [yes] if you want to create the save work, rentrer [cancel] if you want to exit the save processus creation (leave empty to re-enter your process parameters ).
        /// </summary>
        public static string Save_ConfirmChoice {
            get {
                return ResourceManager.GetString("Save.ConfirmChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///! Press enter to continue !.
        /// </summary>
        public static string Save_Continue {
            get {
                return ResourceManager.GetString("Save.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///=&gt; Maximum number of backup processes reached or name or name already taken, unable to create.
        /// </summary>
        public static string Save_ErroLimit {
            get {
                return ResourceManager.GetString("Save.ErroLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///=&gt; Invalid input, please try again.
        /// </summary>
        public static string Save_ErrorInput {
            get {
                return ResourceManager.GetString("Save.ErrorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///=&gt; Invalid save type.
        /// </summary>
        public static string Save_ErrorSaveType {
            get {
                return ResourceManager.GetString("Save.ErrorSaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected entry path: .
        /// </summary>
        public static string Save_InputPath {
            get {
                return ResourceManager.GetString("Save.InputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name of your save.
        /// </summary>
        public static string Save_Name {
            get {
                return ResourceManager.GetString("Save.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected destination path:.
        /// </summary>
        public static string Save_OutputPath {
            get {
                return ResourceManager.GetString("Save.OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///Enter the path of the destination.
        /// </summary>
        public static string Save_PathDestination {
            get {
                return ResourceManager.GetString("Save.PathDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///Enter the path of the file to save.
        /// </summary>
        public static string Save_PathSave {
            get {
                return ResourceManager.GetString("Save.PathSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; Backup process created.
        /// </summary>
        public static string Save_Process {
            get {
                return ResourceManager.GetString("Save.Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of the save project:.
        /// </summary>
        public static string Save_SaveName {
            get {
                return ResourceManager.GetString("Save.SaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///Enter the type of save(0 : All files (chosen by default) / 1 : Changed files).
        /// </summary>
        public static string Save_SaveType {
            get {
                return ResourceManager.GetString("Save.SaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected save type (0 -&gt; Complete, 1 -&gt; Incremental): .
        /// </summary>
        public static string Save_SaveType2 {
            get {
                return ResourceManager.GetString("Save.SaveType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter [yes] to confirm the launch of this save process :.
        /// </summary>
        public static string SaveStart_ConfirmChoice {
            get {
                return ResourceManager.GetString("SaveStart.ConfirmChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , enter [cancel] if you want to cancel the launch of the save process (leave empty to select an other process).
        /// </summary>
        public static string SaveStart_ConfirmChoice2 {
            get {
                return ResourceManager.GetString("SaveStart.ConfirmChoice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch of the save process canceled.
        /// </summary>
        public static string StartSave_Cancel {
            get {
                return ResourceManager.GetString("StartSave.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///! Press enter to continue !.
        /// </summary>
        public static string StartSave_Continue {
            get {
                return ResourceManager.GetString("StartSave.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Error(s) during the save process.
        /// </summary>
        public static string StartSave_Error {
            get {
                return ResourceManager.GetString("StartSave.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name of the backup process to launch.
        /// </summary>
        public static string StartSave_Name {
            get {
                return ResourceManager.GetString("StartSave.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; Backup process started.
        /// </summary>
        public static string StartSave_StartProcess {
            get {
                return ResourceManager.GetString("StartSave.StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; The save process has been completed successfully.
        /// </summary>
        public static string StartSave_Sucess {
            get {
                return ResourceManager.GetString("StartSave.Sucess", resourceCulture);
            }
        }
    }
}
