//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easy_save.Cmd.ConfigurationFiles.Interface_text {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easy_save.Cmd.ConfigurationFiles.Interface_text.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n! Press enter to continue !.
        /// </summary>
        public static string AllProcess_Continue {
            get {
                return ResourceManager.GetString("AllProcess.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; All backup processes have been launched correctly.
        /// </summary>
        public static string AllProcess_EndProcess {
            get {
                return ResourceManager.GetString("AllProcess.EndProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n backup process could not be started.
        /// </summary>
        public static string AllProcess_Error {
            get {
                return ResourceManager.GetString("AllProcess.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start all backup processes.
        /// </summary>
        public static string AllProcess_StartProcess {
            get {
                return ResourceManager.GetString("AllProcess.StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n! Press enter to continue !.
        /// </summary>
        public static string BackupDetails_Continue {
            get {
                return ResourceManager.GetString("BackupDetails.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1| Create a new backup  \n 2| Remove a backup  \n 3| Start a backup  \n 4| Start all available backup processes  \n 5| View backup details  \n 6| Exit.
        /// </summary>
        public static string Main_Menu {
            get {
                return ResourceManager.GetString("Main.Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \nEnter an option:.
        /// </summary>
        public static string Main_Option {
            get {
                return ResourceManager.GetString("Main.Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n! Press enter to continue !.
        /// </summary>
        public static string Remove_Continue {
            get {
                return ResourceManager.GetString("Remove.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n=&gt; Backup process not found.
        /// </summary>
        public static string Remove_MissingFile {
            get {
                return ResourceManager.GetString("Remove.MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name of the backup to delete.
        /// </summary>
        public static string Remove_Name {
            get {
                return ResourceManager.GetString("Remove.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; Backup process removed.
        /// </summary>
        public static string Remove_SucessRemove {
            get {
                return ResourceManager.GetString("Remove.SucessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n! Press enter to continue !.
        /// </summary>
        public static string Save_Continue {
            get {
                return ResourceManager.GetString("Save.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n=&gt; Maximum number of backup processes reached or name or name already taken, unable to create.
        /// </summary>
        public static string Save_ErroLimit {
            get {
                return ResourceManager.GetString("Save.ErroLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n=&gt; Invalid input, please try again.
        /// </summary>
        public static string Save_ErrorInput {
            get {
                return ResourceManager.GetString("Save.ErrorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n=&gt; Invalid save type.
        /// </summary>
        public static string Save_ErrorSaveType {
            get {
                return ResourceManager.GetString("Save.ErrorSaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name of your save.
        /// </summary>
        public static string Save_Name {
            get {
                return ResourceManager.GetString("Save.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \nEnter the path of the destination.
        /// </summary>
        public static string Save_PathDestination {
            get {
                return ResourceManager.GetString("Save.PathDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \nEnter the path of the file to save.
        /// </summary>
        public static string Save_PathSave {
            get {
                return ResourceManager.GetString("Save.PathSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; Backup process created.
        /// </summary>
        public static string Save_Process {
            get {
                return ResourceManager.GetString("Save.Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \nEnter the type of save(0 : All files / 1 : Changed files).
        /// </summary>
        public static string Save_SaveType {
            get {
                return ResourceManager.GetString("Save.SaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n! Press enter to continue !.
        /// </summary>
        public static string StartSave_Continue {
            get {
                return ResourceManager.GetString("StartSave.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n=&gt; Error when launching the save process.
        /// </summary>
        public static string StartSave_Error {
            get {
                return ResourceManager.GetString("StartSave.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name of the backup process to launch.
        /// </summary>
        public static string StartSave_Name {
            get {
                return ResourceManager.GetString("StartSave.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; Backup process started.
        /// </summary>
        public static string StartSave_StartProcess {
            get {
                return ResourceManager.GetString("StartSave.StartProcess", resourceCulture);
            }
        }
    }
}
