//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easy_save.Cmd.ConfigurationFiles.Interface_text {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easy_save.Cmd.ConfigurationFiles.Interface_text.fr", typeof(fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n! Appuyer sur entrée pour continuer !.
        /// </summary>
        public static string AllProcess_Continue {
            get {
                return ResourceManager.GetString("AllProcess.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; Tous les processus de sauvegarde ont été lancés corrêctement.
        /// </summary>
        public static string AllProcess_EndProcess {
            get {
                return ResourceManager.GetString("AllProcess.EndProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n processus de sauvegarde n&apos;a / ont pas pu(s) être lancé(s).
        /// </summary>
        public static string AllProcess_Error {
            get {
                return ResourceManager.GetString("AllProcess.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancement de tout les processus de sauvegarde.
        /// </summary>
        public static string AllProcess_StartProcess {
            get {
                return ResourceManager.GetString("AllProcess.StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n! Appuyer sur entrée pour continuer !.
        /// </summary>
        public static string BackupDetails_Continue {
            get {
                return ResourceManager.GetString("BackupDetails.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1| Créer un processus de sauvegarde  \n 2| Supprimer une sauvegarde  \n 3| Lancer une sauvegarde  \n 4| Lancer tous les processus de sauvegarde disponible \n 5| Afficher les détails de sauvegarde  \n 6| Quitter.
        /// </summary>
        public static string Main_Menu {
            get {
                return ResourceManager.GetString("Main.Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \nChoisir une option:.
        /// </summary>
        public static string Main_Option {
            get {
                return ResourceManager.GetString("Main.Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n! Appuyer sur entrée pour continuer !.
        /// </summary>
        public static string Remove_Continue {
            get {
                return ResourceManager.GetString("Remove.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n=&gt; Processus de sauvegarde non trouvé.
        /// </summary>
        public static string Remove_MissingFile {
            get {
                return ResourceManager.GetString("Remove.MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le nom de la sauvegarde à supprimer.
        /// </summary>
        public static string Remove_Name {
            get {
                return ResourceManager.GetString("Remove.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; Processus de sauvegarde supprimé.
        /// </summary>
        public static string Remove_SucessRemove {
            get {
                return ResourceManager.GetString("Remove.SucessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n! Appuyer sur entrée pour continuer !.
        /// </summary>
        public static string Save_Continue {
            get {
                return ResourceManager.GetString("Save.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n=&gt; Nombre de processus de sauvegarde maximum atteint ou nom déjà choisi, impossible de créer.
        /// </summary>
        public static string Save_ErroLimit {
            get {
                return ResourceManager.GetString("Save.ErroLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n=&gt; Erreur d&apos;entrée, veuillez recommencer.
        /// </summary>
        public static string Save_ErrorInput {
            get {
                return ResourceManager.GetString("Save.ErrorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n=&gt; Type de sauvegarde non valide.
        /// </summary>
        public static string Save_ErrorSaveType {
            get {
                return ResourceManager.GetString("Save.ErrorSaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le nom de la sauvegarde.
        /// </summary>
        public static string Save_Name {
            get {
                return ResourceManager.GetString("Save.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \nEnter le chemin de destination.
        /// </summary>
        public static string Save_PathDestination {
            get {
                return ResourceManager.GetString("Save.PathDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \nEnter le chemin de la sauvegarde.
        /// </summary>
        public static string Save_PathSave {
            get {
                return ResourceManager.GetString("Save.PathSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; Processus de sauvegarde crée.
        /// </summary>
        public static string Save_Process {
            get {
                return ResourceManager.GetString("Save.Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \nEnter le type de sauvegarde (0 =&gt; Tous les fichiers | 1 =&gt; Uniquement les fichiers modifiés).
        /// </summary>
        public static string Save_SaveType {
            get {
                return ResourceManager.GetString("Save.SaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n! Appuyer sur entrée pour continuer !.
        /// </summary>
        public static string StartSave_Continue {
            get {
                return ResourceManager.GetString("StartSave.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n=&gt; Erreur au moment du lancement du processus de sauvegarde.
        /// </summary>
        public static string StartSave_Error {
            get {
                return ResourceManager.GetString("StartSave.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le nom du processus de sauvegarde à lancer.
        /// </summary>
        public static string StartSave_Name {
            get {
                return ResourceManager.GetString("StartSave.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =&gt; Processus de sauvegarde lancé.
        /// </summary>
        public static string StartSave_StartProcess {
            get {
                return ResourceManager.GetString("StartSave.StartProcess", resourceCulture);
            }
        }
    }
}
